<?php


namespace App\Models;

use App\Services\RedisServices;
use Illuminate\Database\Eloquent\Model;

class DetectsClass extends Model
{
    //
    protected $guarded = [];


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function () {
            RedisServices::DetectsClasses(false);
            RedisServices::DetectsClassesName(false);
        });
        self::updated(function () {
            RedisServices::DetectsClasses(false);
            RedisServices::DetectsClassesName(false);
        });
        self::deleted(function () {
            RedisServices::DetectsClasses(false);
            RedisServices::DetectsClassesName(false);
        });

    }

    public function ScopeCustomName($query, $type, $name)
    {

        return $query->where($type, 'like', '%' . $name . '%');
    }

    public function ScopeName($query, $name)
    {

        return $query->where('name', 'like', '%' . $name . '%');
    }
}
